# Generated by Django 4.0 on 2023-03-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images_url',
            field=models.ManyToManyField(blank=True, to='posts.Images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='videos_url',
            field=models.ManyToManyField(blank=True, to='posts.Videos'),
        ),
    ]
