# Generated by Django 4.0 on 2023-03-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images_url',
            field=models.ManyToManyField(blank=True, to='posts.Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='videos_url',
            field=models.ManyToManyField(blank=True, to='posts.Videos'),
        ),
    ]
