# Generated by Django 4.1.7 on 2023-04-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='noOfComment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='noOfLike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videos',
            name='noOfComment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videos',
            name='noOfLike',
            field=models.IntegerField(default=0),
        ),
    ]
