# Generated by Django 4.2 on 2023-04-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_uploadedfile_file_type'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.ManyToManyField(blank=True, to='chats.uploadedfile'),
        ),
    ]
