# Generated by Django 4.1.7 on 2023-04-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='privacy',
            field=models.CharField(choices=[('P', 'Public'), ('F', 'Friends'), ('O', 'Private')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='images_url',
            field=models.ManyToManyField(blank=True, related_name='images', to='posts.image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='videos_url',
            field=models.ManyToManyField(blank=True, related_name='video', to='posts.videos'),
        ),
    ]
