# Generated by Django 4.1.7 on 2023-04-01 03:04

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_image_noofcomment_image_nooflike_videos_noofcomment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image', 'noOfLike', 'noOfComment']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'ordering': ['videos', 'noOfLike', 'noOfComment']},
        ),
        migrations.AlterField(
            model_name='videos',
            name='videos',
            field=models.FileField(upload_to=posts.models.post_videos_rdm_name),
        ),
    ]
