# Generated by Django 4.1.7 on 2023-03-14 23:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_alter_image_id_alter_likepost_id_alter_videos_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postcomment',
            new_name='Comment',
        ),
    ]
