# Generated by Django 4.2 on 2023-04-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_type_comment_comment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='file',
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ManyToManyField(blank=True, to='posts.image'),
        ),
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.ManyToManyField(blank=True, to='posts.videos'),
        ),
    ]
