# Generated by Django 4.2 on 2023-04-27 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_remove_comment_file_comment_image_comment_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharePost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('creator_full_name', models.TextField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('privacy', models.CharField(choices=[('P', 'Public'), ('F', 'Friends'), ('O', 'Only-Me')], default='F', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('NoOflike', models.IntegerField(default=0)),
                ('NoOfcomment', models.IntegerField(default=0)),
                ('media_type', models.IntegerField(default=1)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_post_creator', to=settings.AUTH_USER_MODEL)),
                ('postToShare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_to_share', to='posts.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
