# Generated by Django 4.2 on 2023-05-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_sharepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='likepost',
            name='reactionType',
            field=models.CharField(choices=[('H', 'Happy'), ('L', 'Love'), ('T', 'Like'), ('S', 'Sad'), ('W', 'Wow'), ('A', 'Angry')], default='T', max_length=1),
        ),
    ]
