# Generated by Django 4.1.7 on 2023-04-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='privacy',
            field=models.CharField(choices=[('P', 'Public'), ('F', 'Friends'), ('O', 'OnlyMe')], default='P', max_length=1),
        ),
    ]
