# Generated by Django 4.2 on 2023-05-10 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comment_isdeleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
