# Generated by Django 4.1.7 on 2023-04-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_post_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='privacy',
            field=models.CharField(choices=[('P', 'Public'), ('F', 'Friends'), ('O', 'Only-Me')], default='F', max_length=1),
        ),
    ]
