# Generated by Django 4.1.7 on 2023-04-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_options_alter_post_images_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='NoOflike',
            field=models.IntegerField(default=0),
        ),
    ]
