# Generated by Django 4.1.7 on 2023-04-06 13:02

import cloudinary_storage.storage
from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_likecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=500, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=posts.models.post_rdm_name, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='videos',
            field=models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to=posts.models.post_videos_rdm_name),
        ),
    ]
