# Generated by Django 4.2 on 2023-04-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_videos_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'ordering': ['videos', 'thumbnail']},
        ),
        migrations.RemoveField(
            model_name='videos',
            name='NoOfcomment',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='NoOflike',
        ),
    ]
