# Generated by Django 4.2 on 2023-04-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_videos_options_remove_videos_noofcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='posts_images/thumbnails/'),
        ),
    ]
