# Generated by Django 4.2 on 2023-04-09 12:39

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_image_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image', 'NoOflike', 'NoOfcomment', 'thumbnail']},
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='posts_images/thumbnails/'),
        ),
    ]
