# Generated by Django 4.2 on 2023-04-09 12:59

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_alter_image_options_alter_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='posts_images/thumbnails/', verbose_name='thumbnail'),
        ),
    ]
