# Generated by Django 4.2 on 2023-04-09 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_alter_videos_options_rename_videos_videos_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='video_url',
            new_name='videos',
        ),
    ]
