# Generated by Django 4.2 on 2023-04-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_rename_video_url_videos_videos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'ordering': ['videos', 'thumbnail']},
        ),
    ]
