# Generated by Django 4.2 on 2023-04-10 00:29

import cloudinary_storage.storage
from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_alter_videos_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='videos',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=posts.models.post_videos_rdm_name),
        ),
    ]
