# Generated by Django 4.2 on 2023-04-12 10:40

import cloudinary_storage.storage
from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_alter_image_thumbnail_alter_videos_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='thumbnail',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='videos',
            name='videos',
            field=models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to=posts.models.post_videos_rdm_name, verbose_name='Video'),
        ),
    ]
