# Generated by Django 3.0.5 on 2023-03-14 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby_name', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('bgimg', models.ImageField(default='default-profile-picture_lxgxrl.jpg', upload_to=profiles.models.image_path)),
                ('profileimg', models.ImageField(default='default-profile-picture_lxgxrl.jpg', upload_to=profiles.models.image_path)),
                ('interested', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'None')], default='N', max_length=1)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'None')], default='N', max_length=1)),
                ('location', models.TextField(blank=True, max_length=100)),
                ('school', models.TextField(blank=True, max_length=1500)),
                ('works', models.TextField(blank=True, max_length=500)),
                ('hobby', models.ManyToManyField(blank=True, max_length=200, to='profiles.Hobby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
