# Generated by Django 4.1.7 on 2023-03-11 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowerCount',
        ),
    ]
