# Generated by Django 4.0 on 2023-03-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_delete_followercount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hobby',
            field=models.ManyToManyField(blank=True, max_length=200, to='profiles.Hobby'),
        ),
    ]
