# Generated by Django 4.1.7 on 2023-04-05 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_recentsearch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentsearch',
            options={'ordering': ['date_search']},
        ),
    ]
