# Generated by Django 4.2 on 2023-04-12 10:40

import cloudinary_storage.storage
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_recentsearch_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bgimg',
            field=models.ImageField(default='default-profile-picture_lxgxrl.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=profiles.models.image_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='default-profile-picture_lxgxrl.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=profiles.models.image_path),
        ),
    ]
