# Generated by Django 4.2 on 2023-06-04 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_alter_followercount_id_alter_onlineuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.TextField(max_length=1500)),
                ('ip', models.TextField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to_change', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
