# Generated by Django 4.2 on 2023-04-27 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_publishedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='avatar',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='publishedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 14, 9, 55, 757244, tzinfo=datetime.timezone.utc)),
        ),
    ]
