# Generated by Django 4.2 on 2023-04-27 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_noofshare_alter_news_publishedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='news',
            name='publishedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 15, 38, 56, 465097, tzinfo=datetime.timezone.utc)),
        ),
    ]
