# Generated by Django 4.2 on 2023-05-09 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_news_publishedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publishedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 10, 48, 32, 537842, tzinfo=datetime.timezone.utc)),
        ),
    ]
