# Generated by Django 4.2 on 2023-05-10 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_news_publishedat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='noOfComment',
            new_name='NoOfComment',
        ),
        migrations.AlterField(
            model_name='news',
            name='publishedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 22, 44, 53, 873510, tzinfo=datetime.timezone.utc)),
        ),
    ]
