# Generated by Django 4.2 on 2023-05-22 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_alter_news_publishedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publishedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 6, 47, 21, 631624, tzinfo=datetime.timezone.utc)),
        ),
    ]
