# Generated by Django 4.2 on 2023-05-23 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_alter_news_publishedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publishedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 23, 0, 49, 39, 871196, tzinfo=datetime.timezone.utc)),
        ),
    ]
