# Generated by Django 4.2 on 2023-05-24 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_alter_news_publishedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publishedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 0, 20, 41, 991224, tzinfo=datetime.timezone.utc)),
        ),
    ]
