# Generated by Django 4.2 on 2023-06-04 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_alter_news_publishedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publishedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 8, 15, 3, 426274, tzinfo=datetime.timezone.utc)),
        ),
    ]
