# Generated by Django 4.2 on 2023-06-14 08:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0010_rename_noofcomment_post_noofcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('expiration', models.DateTimeField(default=datetime.datetime(2023, 6, 14, 8, 49, 44, 34403, tzinfo=datetime.timezone.utc))),
                ('no_of_comment', models.IntegerField(default=0)),
                ('no_of_like', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.image')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.videos')),
            ],
        ),
    ]
