# Generated by Django 4.2 on 2023-06-14 08:50

from django.db import migrations, models
import myday.models


class Migration(migrations.Migration):

    dependencies = [
        ('myday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstories',
            name='expiration',
            field=models.DateTimeField(default=myday.models.get_expiration_time),
        ),
    ]
