# Generated by Django 3.0.5 on 2023-03-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegisterCode',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.TextField(max_length=200)),
                ('code', models.IntegerField()),
                ('expiration', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
