# Generated by Django 4.0 on 2023-03-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistercode',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userregistercode',
            name='email',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userregistercode',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
