# Generated by Django 4.2 on 2023-04-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_type',
            field=models.IntegerField(default=1),
        ),
    ]
