# Generated by Django 4.2 on 2023-04-26 03:09

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_uploadedfile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='public_id',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
