# Generated by Django 4.1.7 on 2023-03-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_chatmessage_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='created_time',
            field=models.TimeField(default='17:12:40.470334'),
        ),
        migrations.DeleteModel(
            name='OnlineUser',
        ),
    ]
