# Generated by Django 4.2 on 2023-04-13 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_singleonetooneroom_id_privateroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='singleOneToOneRoom',
        ),
    ]
