# Generated by Django 4.2 on 2023-04-26 03:14

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_uploadedfile_public_id_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='file',
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name=posts.models.Image),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='file',
            field=models.ManyToManyField(blank=True, to='chats.uploadedfile'),
        ),
    ]
