# Generated by Django 3.2.8 on 2023-03-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_chatmessage_created_time_delete_onlineuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateField(default='2023-03-12'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_time',
            field=models.TimeField(default='10:25:50.524993'),
        ),
    ]
