# Generated by Django 4.2 on 2023-04-26 03:15

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_remove_privatemessage_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='video',
            field=models.ImageField(blank=True, upload_to='', verbose_name=posts.models.Videos),
        ),
    ]
