# Generated by Django 3.2.8 on 2023-03-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_auto_20230312_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='created_time',
            field=models.TimeField(default='11:2:7.658487'),
        ),
    ]
