# Generated by Django 3.2.8 on 2023-03-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_alter_chatmessage_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='created_time',
            field=models.TimeField(default='11:52:16.137868'),
        ),
    ]
