# Generated by Django 4.2 on 2023-04-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_comment_file_comment_image_comment_video'),
        ('chats', '0005_privatemessage_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='video',
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='image',
            field=models.ManyToManyField(blank=True, to='posts.image'),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='video',
            field=models.ManyToManyField(blank=True, to='posts.videos'),
        ),
    ]
