# Generated by Django 4.0 on 2023-03-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_hobby'),
        ('chats', '0007_alter_chatmessage_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='created_time',
            field=models.TimeField(default='23:28:12.755355'),
        ),
        migrations.AlterField(
            model_name='room',
            name='subscribers',
            field=models.ManyToManyField(blank=True, to='profiles.Profile'),
        ),
    ]
