# Generated by Django 4.0 on 2023-03-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_alter_chatmessage_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateField(default='2023-03-13'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_time',
            field=models.TimeField(default='2:43:53.578572'),
        ),
    ]
