# Generated by Django 4.0 on 2023-03-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0011_alter_chatmessage_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='created_time',
            field=models.TimeField(default='16:23:10.311854'),
        ),
    ]
