# Generated by Django 4.0 on 2023-03-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_alter_chatmessage_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='created_time',
            field=models.TimeField(default='16:27:10.883395'),
        ),
    ]
