# Generated by Django 4.0 on 2023-03-27 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.TextField(blank=True)),
                ('title', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=1500)),
                ('notifType', models.IntegerField()),
                ('seen', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('singleSubjectUser', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='singlesubjectuser', to='auth.user')),
                ('subjectUser', models.ManyToManyField(related_name='subjectUser', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifyer', to='auth.user')),
            ],
        ),
    ]
