# Generated by Django 4.2 on 2023-05-14 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_room', models.TextField(default=uuid.UUID('e42873e2-cb07-4bd1-a76c-4c984ffb865f'))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification_consumer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectPostsId', models.TextField(blank=True, default=None)),
                ('title', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=1500)),
                ('notifType', models.IntegerField()),
                ('seen', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('subjectUser', models.ManyToManyField(related_name='subjectUser', to=settings.AUTH_USER_MODEL)),
                ('userToNotify', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_to_notify', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['seen', '-date'],
            },
        ),
    ]
