# Generated by Django 4.1.7 on 2023-03-24 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mynotification',
            old_name='tittle',
            new_name='title',
        ),
    ]
