# Generated by Django 4.2 on 2023-05-14 16:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_room',
            field=models.TextField(default=uuid.UUID('efd0ab84-38c7-429d-b2d5-7603dd020061')),
        ),
    ]
