# Generated by Django 4.0 on 2023-03-27 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('notifications', '0002_alter_mynotification_singlesubjectuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynotification',
            name='singleSubjectUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singlesubjectuser', to='auth.user'),
        ),
    ]
