# Generated by Django 4.2 on 2023-05-22 06:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationchannel_channel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_room',
            field=models.TextField(default=uuid.UUID('92a3c486-7a72-4f5e-ac55-179a57f9f665')),
        ),
    ]
