# Generated by Django 4.1.7 on 2023-03-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_tittle_mynotification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynotification',
            name='subject_id',
            field=models.TextField(blank=True),
        ),
    ]
