# Generated by Django 4.0 on 2023-03-27 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_mynotification_singlesubjectuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mynotification',
            name='singleSubjectUser',
        ),
    ]
