# Generated by Django 4.1.7 on 2023-03-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_mynotification_subject_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynotification',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
