# Generated by Django 4.0 on 2023-03-31 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_mynotification_singlesubjectuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mynotification',
            options={'ordering': ('date',)},
        ),
    ]
