# Generated by Django 4.2 on 2023-05-24 00:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notificationchannel_channel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_room',
            field=models.TextField(default=uuid.UUID('4ae83ccd-6781-4a13-8074-498a44751e77')),
        ),
    ]
