# Generated by Django 4.2 on 2023-05-24 00:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notificationchannel_channel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_room',
            field=models.TextField(default=uuid.UUID('5ad6f61b-4b62-4f1f-ac4f-a0b5b441d3ea')),
        ),
    ]
