# Generated by Django 4.2 on 2023-05-24 00:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notificationchannel_channel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_room',
            field=models.TextField(default=uuid.UUID('255dad3f-6169-41da-89dc-9da4d62faa57')),
        ),
    ]
