# Generated by Django 4.2 on 2023-06-04 08:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notificationchannel_channel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_room',
            field=models.TextField(default=uuid.UUID('63871a2d-ee91-46ad-b594-65da8f23943c')),
        ),
    ]
