# Generated by Django 4.2 on 2023-06-14 08:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notificationchannel_channel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_room',
            field=models.TextField(default=uuid.UUID('58ca2a90-ac78-4c9e-898d-788eb2b42001')),
        ),
    ]
