# Generated by Django 4.2 on 2023-06-14 08:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_alter_notificationchannel_channel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_room',
            field=models.TextField(default=uuid.UUID('f26406a8-7d9b-491d-a7d9-573abcf20cc9')),
        ),
    ]
