# Generated by Django 4.2 on 2023-06-14 08:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_alter_notificationchannel_channel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_room',
            field=models.TextField(default=uuid.UUID('9acbf0e7-be26-4570-a19f-b1fad912f2df')),
        ),
    ]
