# Generated by Django 4.2 on 2023-06-14 08:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_alter_notificationchannel_channel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_room',
            field=models.TextField(default=uuid.UUID('4164a6cd-6579-4c7c-9b52-80921670724f')),
        ),
    ]
