# Generated by Django 4.2 on 2023-06-14 08:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_alter_notificationchannel_channel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_room',
            field=models.TextField(default=uuid.UUID('959044d8-dfa2-4377-93ae-773dc870a9ec')),
        ),
    ]
