# Generated by Django 4.2 on 2023-06-14 08:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_alter_notificationchannel_channel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_room',
            field=models.TextField(default=uuid.UUID('5722aee9-f8de-4538-b58a-b79128ac5763')),
        ),
    ]
