# Generated by Django 4.2 on 2023-06-14 08:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0018_alter_notificationchannel_channel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_room',
            field=models.TextField(default=uuid.UUID('d41e333a-c24e-405b-916c-0d435b2fd66c')),
        ),
    ]
