# Generated by Django 4.2 on 2023-06-14 08:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0019_alter_notificationchannel_channel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_room',
            field=models.TextField(default=uuid.UUID('448d8e4b-347f-4f27-b1fc-68f86310bb32')),
        ),
    ]
