# Generated by Django 4.2 on 2023-06-14 08:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0020_alter_notificationchannel_channel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_room',
            field=models.TextField(default=uuid.UUID('a0fde85a-c3be-4bd7-892a-43fe807fc2d7')),
        ),
    ]
