# Generated by Django 4.2 on 2023-06-14 08:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0021_alter_notificationchannel_channel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_room',
            field=models.TextField(default=uuid.UUID('11fcf4d4-7438-476d-b91e-7b5ba895bf32')),
        ),
    ]
