# Generated by Django 4.2 on 2023-06-14 08:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0022_alter_notificationchannel_channel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_room',
            field=models.TextField(default=uuid.UUID('468c1684-f1cf-4d96-b507-61ad6ade4743')),
        ),
    ]
