# Generated by Django 4.2 on 2023-06-14 08:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0024_alter_notificationchannel_channel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_room',
            field=models.TextField(default=uuid.UUID('5d8b41ed-7fb9-4c01-8e3f-1365e9713296')),
        ),
    ]
