# Generated by Django 4.2 on 2023-06-14 08:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0028_alter_notificationchannel_channel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_room',
            field=models.TextField(default=uuid.UUID('6477aaaa-4804-4910-b12b-6c53fc5f7f2b')),
        ),
    ]
