# Generated by Django 4.2 on 2023-06-14 08:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0029_alter_notificationchannel_channel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_room',
            field=models.TextField(default=uuid.UUID('7622cf21-6a38-4acc-8152-b74ba59eff2f')),
        ),
    ]
