# Generated by Django 4.2 on 2023-06-14 08:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0032_alter_notificationchannel_channel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_room',
            field=models.TextField(default=uuid.UUID('96923d90-e8b4-4358-afdf-60c257ab380e')),
        ),
    ]
