# Generated by Django 4.2 on 2023-06-14 08:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0033_alter_notificationchannel_channel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_room',
            field=models.TextField(default=uuid.UUID('98a02fba-d70f-4e8e-8bdd-ec4706fbdbc1')),
        ),
    ]
