# Generated by Django 4.2 on 2023-06-14 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0034_alter_notificationchannel_channel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_room',
            field=models.TextField(default=uuid.UUID('968b913e-7f75-4425-8388-0dcc6c74421d')),
        ),
    ]
