# Generated by Django 4.2 on 2023-06-14 08:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0036_alter_notificationchannel_channel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_room',
            field=models.TextField(default=uuid.UUID('ef1d6e88-52a2-4b95-b7dd-f92ad9b083cd')),
        ),
    ]
