# Generated by Django 4.2 on 2023-10-12 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0037_alter_notificationchannel_channel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_room',
            field=models.TextField(default=uuid.UUID('3bae7a8f-d46d-4d71-8917-cfd9002fc3b7')),
        ),
    ]
